name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Worls
        run: echo "Hello NDC"
        
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 12.x
